apiVersion: v1
kind: ReplicationController
metadata:
  name: rctomcat
spec:
  replicas: 1
  selector:
    app: tomcat
  template:
    metadata:
      name: tomcat
      labels:
        app: tomcat
    spec:
      containers:
      - name: rctomcat
        image: bitnami/tomcat
        ports:
        - containerPort: 8080
