apiVersion: batch/v1
kind: Job
metadata:
  name: pythonjob
spec:
  template:
    spec:
      containers:
      - name: pythonjob
        image: python
        command: ["python",  "-c", "success"]
      restartPolicy: Never
  backoffLimit: 4
