apiVersion: v1
kind: Pod
metadata:
  name: mypodenv1
spec:
  containers:
  - name: podwithenvc
    image: jenkinsci/blueocean
    ports:
    - containerPort: 8080
    env:
    - name: JENKINS_POD_VERSION
      value: "1.0"

